steps:
  - name: 'gcr.io/$PROJECT_ID/holocron:latest'
    entrypoint: sh
    args: 
      - "-c"
      - |
        cat /secrets/$_ENV/environments/${_SERVICE_NAME}.env > .env
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME', '-f', 'Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'run', 'deploy', '$_SERVICE_NAME', '--image', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME', '--region', '$_REGION','--platform', 'managed', '--quiet', '--allow-unauthenticated']
timeout: 600s

substitutions:
  _ENV: staging
  _SERVICE_NAME: 'shuttlecraft'
  _REGION: asia-southeast1
